version: "3.6"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:rw
    depends_on:
      - mysql
      - phpmyadmin
    container_name: php-server
  mysql:
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bdreservoir
    restart: always
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
